services:
  grafana:
    # image: grafana/grafana:10.1.1
    image: grafana/grafana-enterprise:10.1.1
    container_name: grafana-sentry-datasource
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana    
      - ~/work/grafana/license.jwt:/var/lib/grafana/data/license.jwt 
      - ./:/var/lib/grafana/plugins/grafana-sentry-datasource
      # - ./pkg/mocker/testdata:/mock/grafana-sentry-datasource/testdata
      - ./provisioning:/etc/grafana/provisioning
    environment:
      - TERM=linux
      - GF_DEFAULT_APP_MODE=development
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_USERS_VIEWERS_CAN_EDIT=true
      # - GF_ENTERPRISE_LICENSE_TEXT=
      # - E2E_GRAFANA_VERSION=${E2E_GRAFANA_VERSION}
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-sentry-datasource
      # - GRAFANA_SENTRY_MOCK_SOURCE=local_mock
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_BASIC_ENABLED=false
      - GF_LOG_LEVEL=debug
      - GF_DATAPROXY_LOGGING=true
      - GF_CACHING_ENABLED=true
      - GF_ENTERPRISE_LICENSE_PATH=/var/lib/grafana/data/license.jwt 
      # - GF_SERVER_ROOT_URL=http://localhost:3000/

volumes:
  grafana-data: {}